services:
  wrf-runs:
    build:
      context: ../
      dockerfile: gfortran_wvt/Dockerfile
    image: mullenkamp/wrf-auto-runs-wvt:1.2
    shm_size: '1gb'
    volumes:
        - "./parameters.toml:/app/parameters.toml"
        - ~/WPS_GEOG:/WPS_GEOG
